class CreateSubproducts < ActiveRecord::Migration
  def change
    create_table :subproducts do |t|
      t.references :product, :null => false
      t.string :name, :null => false
      t.timestamps
    end
    Subproduct.create :name => "Advertising & Marketing", :product_id => 1
    Subproduct.create :name => "Accounting and Finance", :product_id => 1
    Subproduct.create :product_id => 1, :name => "Angels and Private Equity"
    Subproduct.create :product_id => 1, :name => "Business planning"
    Subproduct.create :product_id => 1, :name => "Careers & Employment services"
    Subproduct.create :product_id => 1, :name => "Ecommerce"
    Subproduct.create :product_id => 1, :name => "Employment and labor issues"
    Subproduct.create :product_id => 1, :name => "Entrepreneurs"
    Subproduct.create :product_id => 1, :name => "Financial Planning"
    Subproduct.create :product_id => 1, :name => "Corporations"
    Subproduct.create :product_id => 1, :name => "Credit & Debit"
    Subproduct.create :product_id => 1, :name => "General Management"
    Subproduct.create :product_id => 1, :name => "Insurance"    
    Subproduct.create :product_id => 1, :name => "International Business and Operations"
    Subproduct.create :product_id => 1, :name => "Mortgage and Loans"
    Subproduct.create :product_id => 1, :name => "Stock trading and Investing"
    Subproduct.create :product_id => 1, :name => "Personal Finance"
    Subproduct.create :product_id => 1, :name => "Renting & Real Estate"
    Subproduct.create :product_id => 1, :name => "Small Business"
    Subproduct.create :product_id => 1, :name => "Taxes"
    Subproduct.create :product_id => 1, :name => "Translation services"
    Subproduct.create :product_id => 1, :name => "Transcription services"
    Subproduct.create :product_id => 1, :name => "Other - Business & Finance"
    Subproduct.create :product_id => 2, :name => "Corporate law"
    Subproduct.create :product_id => 2, :name => "Criminal law"
    Subproduct.create :product_id => 2, :name => "Driving, Accidents and Personal injury"
    Subproduct.create :product_id => 2, :name => "Family and Divorce laws"
    Subproduct.create :product_id => 2, :name => "Immigration law"
    Subproduct.create :product_id => 2, :name => "Insurance Law"
    Subproduct.create :product_id => 2, :name => "Legal research"
    Subproduct.create :product_id => 2, :name => "Paralegal services"
    Subproduct.create :product_id => 2, :name => "Tax law"
    Subproduct.create :product_id => 2, :name => "Wills and Trust"
    Subproduct.create :product_id => 3, :name => "Building self-esteem and confidence"
    Subproduct.create :product_id => 3, :name => "Career counseling"
    Subproduct.create :product_id => 3, :name => "Interpersonal communication"
    Subproduct.create :product_id => 3, :name => "Motivation"
    Subproduct.create :product_id => 3, :name => "Personal development"
    Subproduct.create :product_id => 3, :name => "Stress and Anger management"
    Subproduct.create :product_id => 3, :name => "Time management"
    Subproduct.create :product_id => 3, :name => "Work life balance"
    Subproduct.create :product_id => 3, :name => "others"
    Subproduct.create :product_id => 4, :name => "Crisis management"
    Subproduct.create :product_id => 4, :name => "Dating issues"
    Subproduct.create :product_id => 4, :name => "Drug Addiction"
    Subproduct.create :product_id => 4, :name => "Eating disorders"
    Subproduct.create :product_id => 4, :name => "Emotional disorders"
    Subproduct.create :product_id => 4, :name => "Parenting"
    Subproduct.create :product_id => 4, :name => "Pastoral and Christian counseling"
    Subproduct.create :product_id => 4, :name => "Personal Relationships"
    Subproduct.create :product_id => 4, :name => "Others"
    Subproduct.create :product_id => 5, :name => "Application Development"
    Subproduct.create :product_id => 5, :name => "Computer & Video Games"
    Subproduct.create :product_id => 5, :name => "Computer Repair"
    Subproduct.create :product_id => 5, :name => "Internet Crawling services"
    Subproduct.create :product_id => 5, :name => "Databases"
    Subproduct.create :product_id => 5, :name => "Handhelds/PDAs"
    Subproduct.create :product_id => 5, :name => "Hardware"
    Subproduct.create :product_id => 5, :name => "Help For Beginners"
    Subproduct.create :product_id => 5, :name => "Internet Searches"
    Subproduct.create :product_id => 5, :name => "Microsoft Excel Help"
    Subproduct.create :product_id => 5, :name => "Middleware"
    Subproduct.create :product_id => 5, :name => "Networking"
    Subproduct.create :product_id => 5, :name => "Office Software"
    Subproduct.create :product_id => 5, :name => "Operating System"
    Subproduct.create :product_id => 5, :name => "Windows"
    Subproduct.create :product_id => 5, :name => "Linux"
    Subproduct.create :product_id => 5, :name => "MAC"
    Subproduct.create :product_id => 5, :name => "Ubuntu"
    Subproduct.create :product_id => 5, :name => "Other (Computers & Programming)"
    Subproduct.create :product_id => 5, :name => "Programming"
    Subproduct.create :product_id => 5, :name => "Security & Encryption"
    Subproduct.create :product_id => 5, :name => "System Administration"
    Subproduct.create :product_id => 5, :name => "Telecommunication"
    Subproduct.create :product_id => 5, :name => "Web Development"
    Subproduct.create :product_id => 5, :name => "Website Partners"
    Subproduct.create :product_id => 5, :name => "Wireless Technologies"
    Subproduct.create :product_id => 6, :name => "Services"
    Subproduct.create :product_id => 6, :name => "Alternate Medicine"
    Subproduct.create :product_id => 6, :name => "Child & Adolescent Health"
    Subproduct.create :product_id => 6, :name => "Chiropractic Medicine"
    Subproduct.create :product_id => 6, :name => "Cosmetics"
    Subproduct.create :product_id => 6, :name => "Diet & Nutrition"
    Subproduct.create :product_id => 6, :name => "Disabilities"
    Subproduct.create :product_id => 6, :name => "Disorders and Conditions"
    Subproduct.create :product_id => 6, :name => "Drugs and Medicines"
    Subproduct.create :product_id => 6, :name => "Emergency Medicine"
    Subproduct.create :product_id => 6, :name => "Health for Women"
    Subproduct.create :product_id => 6, :name => "Health Insurance and Plans"
    Subproduct.create :product_id => 6, :name => "Infertility"
    Subproduct.create :product_id => 6, :name => "Medical Education"
    Subproduct.create :product_id => 6, :name => "Medical Ethics"
    Subproduct.create :product_id => 6, :name => "Medical Publications"
    Subproduct.create :product_id => 6, :name => "Mental & Emotional Health"
    Subproduct.create :product_id => 6, :name => "Non Clinical"
    Subproduct.create :product_id => 6, :name => "Nursing"
    Subproduct.create :product_id => 6, :name => "Occupational Therapy"
    Subproduct.create :product_id => 6, :name => "Parenting"
    Subproduct.create :product_id => 6, :name => "Pain and Pain management"
    Subproduct.create :product_id => 6, :name => "Personal Fitness"
    Subproduct.create :product_id => 6, :name => "Pharmacology"
    Subproduct.create :product_id => 6, :name => "Physical Therapy"
    Subproduct.create :product_id => 6, :name => "Pregnancy & Childbirth"
    Subproduct.create :product_id => 6, :name => "Public & Environmental Health"
    Subproduct.create :product_id => 6, :name => "Psychological health"
    Subproduct.create :product_id => 6, :name => "Respiratory Therapy"
    Subproduct.create :product_id => 6, :name => "Sexual health and disorders"
    Subproduct.create :product_id => 6, :name => "Specialty Medicine"
    Subproduct.create :product_id => 6, :name => "Speech Therapy"
    Subproduct.create :product_id => 7, :name => "Arts and Antique collection"
    Subproduct.create :product_id => 7, :name => "Beauty & Style"
    Subproduct.create :product_id => 7, :name => "Cooking & Food"
    Subproduct.create :product_id => 7, :name => "Electronics & Gadgets"
    Subproduct.create :product_id => 7, :name => "Event and Party management"
    Subproduct.create :product_id => 7, :name => "Garden & Landscaping"
    Subproduct.create :product_id => 7, :name => "General"
    Subproduct.create :product_id => 7, :name => "Green Living"
    Subproduct.create :product_id => 7, :name => "Homeownership"
    Subproduct.create :product_id => 7, :name => "Pets"
    Subproduct.create :product_id => 7, :name => "Shopping"
    Subproduct.create :product_id => 7, :name => "Others"
    Subproduct.create :product_id => 8, :name => "Astrology"
    Subproduct.create :product_id => 8, :name => "Career Forecasts"
    Subproduct.create :product_id => 8, :name => "Dream Analysis"
    Subproduct.create :product_id => 8, :name => "Financial Outlook"
    Subproduct.create :product_id => 8, :name => "Fortune Telling"
    Subproduct.create :product_id => 8, :name => "Graphology"
    Subproduct.create :product_id => 8, :name => "Love & Relationships"
    Subproduct.create :product_id => 8, :name => "New Age Spirituality"
    Subproduct.create :product_id => 8, :name => "Numerology"
    Subproduct.create :product_id => 8, :name => "Occult"
    Subproduct.create :product_id => 8, :name => "Palm Reading"
    Subproduct.create :product_id => 8, :name => "Paranormal"
    Subproduct.create :product_id => 8, :name => "Picture Readings"
    Subproduct.create :product_id => 8, :name => "Psychic Reading"
    Subproduct.create :product_id => 8, :name => "Religion"
    Subproduct.create :product_id => 8, :name => "Tarot Reading"
    Subproduct.create :product_id => 8, :name => "Vedic Astrology"
    Subproduct.create :product_id => 9, :name => "Antiques"
    Subproduct.create :product_id => 9, :name => "Crafts"
    Subproduct.create :product_id => 9, :name => "Event Management"
    Subproduct.create :product_id => 9, :name => "Film & Video"
    Subproduct.create :product_id => 9, :name => "Food & Drink"
    Subproduct.create :product_id => 9, :name => "Graphic and Desktop Design"
    Subproduct.create :product_id => 9, :name => "Media Communications"
    Subproduct.create :product_id => 9, :name => "Music"
    Subproduct.create :product_id => 9, :name => "Performing Arts"
    Subproduct.create :product_id => 9, :name => "Photography"
    Subproduct.create :product_id => 9, :name => "Technical Writing services"
    Subproduct.create :product_id => 9, :name => "Web Design"
    Subproduct.create :product_id => 9, :name => "Visual Arts"
    Subproduct.create :product_id => 9, :name => "Writing Services"
  end
end
